### ISSUE TITLE
Error 'Unable to verify your data submission.'

### ISSUE THREAD

**Issue by drtsb** [onmotion/yii2-telegram#1]
Hi!

I've tried to install extension according to installation guide. When I'm trying to login to chat, telegram server sends request to https://myhost.com/telegram/default/hook which throws following error:

> 2016-10-22 17:01:27 [149.154.167.206][-][-][error][yii\web\HttpException:400] exception 'yii\web\BadRequestHttpException' with message 'Unable to verify your data submission.' in /home/u56097/3dlab.site/vendor/yiisoft/yii2/web/Controller.php:110 Stack trace:
> # 0 /home/u56097/3dlab.site/vendor/yiisoft/yii2/base/Controller.php(152): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
> # 1 /home/u56097/3dlab.site/vendor/yiisoft/yii2/base/Module.php(454): yii\base\Controller->runAction('hook', Array)
> # 2 /home/u56097/3dlab.site/vendor/yiisoft/yii2/web/Application.php(100): yii\base\Module->runAction('telegram/defaul...', Array)
> # 3 /home/u56097/3dlab.site/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
> # 4 /home/u56097/3dlab.site/frontend/web/index.php(18): yii\base\Application->run()
> # 5 {main}

It looks like a problem with csrf token validation. So I had to add following code to \onmotion\telegram\controllers\DefaultController.php

```
use Yii;

public function beforeAction($action){            
    if ($action->id == 'hook') {
        $this->enableCsrfValidation = false;
    }
    return parent::beforeAction($action);
}
```

which solved a problem, but I'm not sure that this is a good decision.

Waiting for response and thanks for this great extension!

**Comment by onmotion** [comment]
Hi!

You are absolutely right, it's my mistake, I forgot to change config while testing module... Your desigion work fine, this action doesn't need csrf token, it listen requests from external telegram server.

Thank you! Have a nice day!
