### ISSUE TITLE
не работаетют пользовательские команды

### ISSUE THREAD

**Issue by alexeydg** [onmotion/yii2-telegram#13]
Добрый день, скопировал как в мануале папку в @app/modules/telegram/UserCommands, раскомментировал в конфиге, не работает, изменил путь в конфигах на app\modules\telegram\UserCommands , тоже не работают, тестирую на /weather пишет такой команды нет

**Comment by onmotion** [comment]
**/help** команда работает?
Вы полностью весь модуль скопировали?
у вас advanced или basic? Посмотрите в приложении как резолвится путь с `\Yii::getAlias()`.

**Comment by alexeydg** [comment]
хелп работает но показывается только первоначальные ваши команды их там штуки 4, скопировал как и описано в мануале только папку UserCommands, у меня basic, путь проверю

**Comment by alexeydg** [comment]
\Yii::getAlias() все впорядке

**Comment by onmotion** [comment]
Попробуйте поставить точку останова в setWebhook, например
```php
if (!empty(\Yii::$app->modules['telegram']->userCommandsPath)){
                if(!$commandsPath = realpath(\Yii::getAlias(\Yii::$app->modules['telegram']->userCommandsPath))){
                    $commandsPath = realpath(\Yii::getAlias('@app') . \Yii::$app->modules['telegram']->userCommandsPath);
                }
                if(!is_dir($commandsPath)) throw new UserException('dir ' . \Yii::$app->modules['telegram']->userCommandsPath . ' not found!');
            }
```

и посмотрите Xdebug'ом (ну или var_dump) что там происходит

**Comment by alexeydg** [comment]
как надо правильно копировать модуль? может я просто не так скопировал? надо весь модуль целиком копировать в app/modules ?

**Comment by onmotion** [comment]
Сам модуль копировать не нужно, вам нужно лишь указать путь к дополнительным командам. Все команды в модуле приведены для примера. Просто указали путь где модулю искать команды и набросали туда своих команд.

![2018-10-29_11-11-33](https://user-images.githubusercontent.com/12899080/47637032-75d9ed00-db6b-11e8-8116-2aac8db3cf59.png)

**Comment by alexeydg** [comment]
да все так и сделано, но бот их не видит в упор

**Comment by alexeydg** [comment]
realpath(\Yii::getAlias('@app') . \Yii::$app->modules['telegram']->userCommandsPath возращает пустоту вот видимо в чем беда

**Comment by alexeydg** [comment]
а если переделать на вот так \Yii::getAlias(\Yii::$app->modules['telegram']->userCommandsPath) то путь верный. баг?

**Comment by onmotion** [comment]
Именно он сначала и проверяется `if(!$commandsPath = realpath(\Yii::getAlias(\Yii::$app->modules['telegram']->userCommandsPath))){`

**Comment by alexeydg** [comment]
ну да, даже изменив путь на /modules/telegram/UserCommands в общем ничего не поменялось, команды юзерские не пашет, хотя модуль папку с ними видит все впорядке

**Comment by alexeydg** [comment]
а в каком экшене вообще вызываются команды присланные от бота? чтото не вижу

**Comment by onmotion** [comment]
У вас namespace корректный указан в ваших пользовательских командах? Для вашего пути должен быть `modules\telegram\UserCommands;`

**Comment by alexeydg** [comment]
да вы правы, но этого не было в манах, а так сразу и не додумаешься. все работает спс

**Comment by alexeydg** [comment]
пишу 
/date Moscow
отвечает
You must specify location in format: /date <city>

каков формат команд?

**Comment by onmotion** [comment]
Команды для примера взяты у Longman. Они на то и пользовательские, потому что пользователь должен писать из сам. Зайдите внутрь посмотрите что в экшне делается. Самая простая команда echo

**Comment by onmotion** [comment]
> не было в манах

Добавил
