### ISSUE TITLE
Баги с пользовательскими командами

### ISSUE THREAD

**Issue by alexeydg** [onmotion/yii2-telegram#14]
в продолжение утренних проблем.
Ок бот стал видеть юзерские команды, если из папки удалить ненужные, он в списке видит только не удаленные, если в папку @app\modules\UserCommands добавить новую свою команду или например у существующей команды изменить описание то бот этого не увидит, как итог, список команд бот видит в перечне @app\modules\UserCommands (причем если добавить свой контроллер команд то он его не увидит), а при выполнении /help описание команд берет уже из vendor. вот такие дела, как итог свои команды не написать =(

**Comment by alexeydg** [comment]
а да и еще отваливается команда /login т е полдня работала, можно было ввести пароль и все ок,  а потом просто вводишь пароль и ничего

**Comment by onmotion** [comment]
Верните namespace обратно, только что проверил изменив echo на echos, все работает
```php
namespace Longman\TelegramBot\Commands\UserCommands;

use Longman\TelegramBot\Commands\UserCommand;
use Longman\TelegramBot\Request;

/**
 * User "/echos" command
 */
class EchosCommand extends UserCommand
{
    /**#@+
     * {@inheritdoc}
     */
    protected $name = 'echos';
    protected $description = 'Show text';
    protected $usage = '/echos <text>';
    protected $version = '1.0.1';
    public $enabled = true;
```

**Comment by alexeydg** [comment]
в общем любые изменение в командах ,что в вендоре, что в юзерской папке никак не влияют на команды в боте, как будто он их кеширует, даже смена версии не помогает

**Comment by alexeydg** [comment]
чудеса но сменив обратно неймспейс все заработало
