### ISSUE TITLE
At the moment, there are no available operators. Please, try to write later.

### ISSUE THREAD

**Issue by epilim200** [onmotion/yii2-telegram#15]
Hi,

I stuck when send any message they always reply "At the moment, there are no available operators. Please, try to write later". How to login on server side?

Thanks.

**Comment by epilim200** [comment]
![image](https://user-images.githubusercontent.com/12898501/47779321-cdc35000-dd33-11e8-852f-e0381c9a299b.png)

nothing happen

**Comment by onmotion** [comment]
Did you add bot to chat? Can he get commands? Check settings in BotFather

--
WBR, Alexandr Kozhevnikov
onmotion1@gmail.com

**Comment by epilim200** [comment]
I already add bot in group chat, but when i type the command nothing happen

**Comment by onmotion** [comment]
What do you see if type /help?

--
WBR, Alexandr Kozhevnikov
onmotion1@gmail.com

**Comment by onmotion** [comment]
Your bot doesn't receive commands. Please read the telegram bot docs.

--
WBR, Alexandr Kozhevnikov
onmotion1@gmail.com

**Comment by epilim200** [comment]
for your info, im using ngrok to get https...is it working with ngrok?

**Comment by onmotion** [comment]
Firstly make your bot work properly. It's not depends from the module.

--
WBR, Alexandr Kozhevnikov
onmotion1@gmail.com

**Comment by epilim200** [comment]
ok thanks. I will make sure my bot is working properly first

**Comment by epilim200** [comment]
Hi,

I check with telegram api getWebhookInfo...

{"ok":true,"result":{"url":"https://mydomain.com/index.php?r=telegram/default/hook","has_custom_certificate":false,"pending_update_count":33,"last_error_date":1541058222,"last_error_message":"Wrong response from the webhook: 302 Found","max_connections":40}}

**Comment by onmotion** [comment]
https://mydomain.com ??

**Comment by epilim200** [comment]
its just for example

{"ok":true,"result":{"url":"https://b16815e0.ngrok.io/index.php?r=telegram/default/hook","has_custom_certificate":false,"pending_update_count":33,"last_error_date":1541063102,"last_error_message":"Wrong response from the webhook: 302 Found","max_connections":40}}

**Comment by epilim200** [comment]
I remove this in my config component...and now its working...how can this telegram chat working with access control?

'as beforeRequest' => [
        'class' => 'yii\filters\AccessControl',
        'rules' => [
            [
                'allow' => true,
                'actions' => [
                    'login',
                    'forgot-password',
                    'timeoffresponsebyemail',
                    'leaveendorsebyemail',
                    'leaveapprovebyemail'
                ],
            ],
            [
                'allow' => true,
                'roles' => ['@'],
            ],
        ],
        'denyCallback' => function () {
            return Yii::$app->response->redirect(['site/login']);
        },
    ],
    'as access' => [
        'class' => '\hscstudio\mimin\components\AccessControl',
            'allowActions' => [
                   // add wildcard allowed action here!
                   'site/*',
                   'debug/*',
                   'mimin/*', // only in dev mode
                   'administrator/*',
                   'gii/*',
            ],
    ],

**Comment by onmotion** [comment]
Ok, I checked the url https://b16815e0.ngrok.io/index.php?r=telegram/default/hook <https://b16815e0.ngrok.io/index.php?r=telegram/default/hook> and first time I got 302 (redirect to login page - remove authorization for this url), the second time I have got 500, then 429 Too many requests.
—
WBR, Alexandr Kozhevnikov

**Comment by epilim200** [comment]
/help is working but /login is not working...return error 500

![image](https://user-images.githubusercontent.com/12898501/47843605-214ca100-ddfb-11e8-8e68-dd905f85926c.png)

**Comment by onmotion** [comment]
So this mean your host returns 500. Check why

--
WBR, Alexandr Kozhevnikov
onmotion1@gmail.com

**Comment by epilim200** [comment]
now its return

![image](https://user-images.githubusercontent.com/12898501/47844024-4988cf80-ddfc-11e8-8d53-bfa07796b28e.png)

**Comment by epilim200** [comment]
/login still not response but hook is working now

![image](https://user-images.githubusercontent.com/12898501/47844309-0bd87680-ddfd-11e8-925a-0bb8ad619860.png)

**Comment by epilim200** [comment]
ok i think something wrong on my system...I will check by myself

Thanks
