### ISSUE TITLE
ошибка в console

### ISSUE THREAD

**Issue by alexeydg** [onmotion/yii2-telegram#16]
из мануала

> and to console config:

 'bootstrap' => [   
 //other bootstrap components...
                'telegram'],

при запуске любой консольной программы выдает

> Error: Please configure UrlManager::scriptUrl correctly as you are running a console application
как только убираю из bootstrap телеграм, все пашет

**Comment by onmotion** [comment]
Это требуется лишь для работы консольных команд, если вам они не нужны, не
делайте этого, если нужны, сконфигурируйте urlManager для консоли.

--
WBR, Alexandr Kozhevnikov
onmotion1@gmail.com
