### ISSUE TITLE
postgresql migration

### ISSUE THREAD

**Issue by gucluaydogan** [onmotion/yii2-telegram#4]
I am using postgresql as database and when I tried to apply migration I get the error:

*** applying m160808_112253_onmotion_yii2_telegram
    > create table tlgrm_actions ... done (time: 0.028s)
    > add primary key PK on tlgrm_actions (chat_id) ... done (time: 0.017s)
    > create table tlgrm_auth_mngr_chats ... done (time: 0.012s)
    > add primary key PK on tlgrm_auth_mngr_chats (chat_id) ...Exception: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "PK" already exists
The SQL being executed was: ALTER TABLE "tlgrm_auth_mngr_chats" ADD CONSTRAINT "PK"  PRIMARY KEY ("chat_id" ) (/home/guclu/workspace/vdmcworld/vendor/yiisoft/yii2/db/Schema.php:631)

Problem is the name of the keys. They cannot have the same name. (PK in this case) I changed the names, after that everything went fine... FYI

Thanks for the extension.

**Comment by onmotion** [comment]
Sorry for the long wait. Thanks for report.
