### ISSUE TITLE
Предложение вынести идентификатор клиента в конфиг

### ISSUE THREAD

**Issue by dark46** [onmotion/yii2-telegram#6]
Привет! У меня к примеру нет getIdentity()->username, но есть getIdentity()->login, предлагаю данный параметр вынести в конфиг настраиваемым.

В файле Commands/YiiChatCommand.php:
```
 try{
                $yiiUsername = Yii::$app->getUser()->getIdentity()->username;
            } catch (\Exception $e){
                $yiiUsername = 'guest';     
            }
```

**Comment by onmotion** [comment]
Привет.

Хорошая идея, сделаю как только появится свободная минута. Либо с радостью приму ваш pull request :)
